In [33]:
import numpy as np

## Data types and attributes

In [34]:
# Numpy's main datatype is ndarray

In [35]:
a1 = np.array([1, 2, 3, 4, 5])

In [36]:
type(a1)

numpy.ndarray

In [37]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5.5, 6.0]])

In [38]:
type(a2)

numpy.ndarray

In [39]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [ 7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [40]:
type(a3)

numpy.ndarray

In [41]:
a1 # array, vector, 1 dimension, shape 1,5

array([1, 2, 3, 4, 5])

In [42]:
a2 # array, maxtrix, 2 dimension or more, shape 2, 3
# automatically convert all the data to float, ndarray only can be of one type

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [43]:
a3 # array, matrix, 3 dimension, shape, 2,3,3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
np.shape(a1)

(5,)

In [45]:
np.shape(a2)

(2, 3)

In [46]:
np.shape(a3)

(2, 3, 3)

In [47]:
# print dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [48]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [49]:
a1.size, a2.size, a3.size

(5, 6, 18)

In [50]:
a1, a2, a3

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3.3],
        [4. , 5.5, 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [51]:
# no matter what type or shape the array is, the type allways is ndarray, is an universal data type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [52]:
# create a dataframe from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.5  6.0

## Creating arrays

In [53]:
ones = np.ones((2, 3))

In [54]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
ones.dtype

dtype('float64')

In [56]:
ones2 = np.ones((3,3), int)

In [57]:
ones2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
ones2.dtype

dtype('int64')

In [61]:
type(ones)

numpy.ndarray

In [62]:
zeros = np.zeros((4,3))

In [63]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [66]:
random_array = np.random.randint(0, 10, size=(4, 5))
random_array

array([[3, 4, 2, 8, 0],
       [6, 2, 8, 9, 1],
       [6, 6, 9, 8, 5],
       [2, 6, 2, 2, 1]])

In [67]:
random_array.size

20

In [68]:
random_array.shape

(4, 5)

In [75]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.72892125, 0.06421522, 0.60771274],
       [0.41730883, 0.46433743, 0.49168791],
       [0.89269277, 0.65633606, 0.51808368],
       [0.25491571, 0.54040478, 0.11052389],
       [0.00112798, 0.16174867, 0.72999124]])

In [76]:
random_array_2.shape

(5, 3)

In [83]:
random_array_3 = np.random.rand(4, 3)
random_array_3

array([[0.05275808, 0.88738467, 0.90600743],
       [0.10923029, 0.4131233 , 0.082418  ],
       [0.86264006, 0.37091901, 0.26717534],
       [0.6111785 , 0.77873533, 0.26454665]])

In [92]:
# Pseudo-random numbers
# random seed make reproducible results every time, alligned with the seed
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(4, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [98]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])