In [33]:
import numpy as np

## Data types and attributes

In [34]:
# Numpy's main datatype is ndarray

In [35]:
a1 = np.array([1, 2, 3, 4, 5])

In [36]:
type(a1)

numpy.ndarray

In [37]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5.5, 6.0]])

In [38]:
type(a2)

numpy.ndarray

In [39]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [ 7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [40]:
type(a3)

numpy.ndarray

In [41]:
a1 # array, vector, 1 dimension, shape 1,5

array([1, 2, 3, 4, 5])

In [42]:
a2 # array, maxtrix, 2 dimension or more, shape 2, 3
# automatically convert all the data to float, ndarray only can be of one type

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [43]:
a3 # array, matrix, 3 dimension, shape, 2,3,3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
np.shape(a1)

(5,)

In [45]:
np.shape(a2)

(2, 3)

In [46]:
np.shape(a3)

(2, 3, 3)

In [47]:
# print dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [48]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [49]:
a1.size, a2.size, a3.size

(5, 6, 18)

In [50]:
a1, a2, a3

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3.3],
        [4. , 5.5, 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [51]:
# no matter what type or shape the array is, the type allways is ndarray, is an universal data type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [52]:
# create a dataframe from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.5  6.0

## Creating arrays

In [53]:
ones = np.ones((2, 3))

In [54]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
ones.dtype

dtype('float64')

In [56]:
ones2 = np.ones((3,3), int)

In [57]:
ones2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
ones2.dtype

dtype('int64')

In [61]:
type(ones)

numpy.ndarray

In [62]:
zeros = np.zeros((4,3))

In [63]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [66]:
random_array = np.random.randint(0, 10, size=(4, 5))
random_array

array([[3, 4, 2, 8, 0],
       [6, 2, 8, 9, 1],
       [6, 6, 9, 8, 5],
       [2, 6, 2, 2, 1]])

In [67]:
random_array.size

20

In [68]:
random_array.shape

(4, 5)

In [75]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.72892125, 0.06421522, 0.60771274],
       [0.41730883, 0.46433743, 0.49168791],
       [0.89269277, 0.65633606, 0.51808368],
       [0.25491571, 0.54040478, 0.11052389],
       [0.00112798, 0.16174867, 0.72999124]])

In [76]:
random_array_2.shape

(5, 3)

In [83]:
random_array_3 = np.random.rand(4, 3)
random_array_3

array([[0.05275808, 0.88738467, 0.90600743],
       [0.10923029, 0.4131233 , 0.082418  ],
       [0.86264006, 0.37091901, 0.26717534],
       [0.6111785 , 0.77873533, 0.26454665]])

In [92]:
# Pseudo-random numbers
# random seed make reproducible results every time, alligned with the seed
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(4, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [98]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [101]:
random_array_6 = np.random.randint(0, 10, size=(4, 3))
random_array_6

array([[4, 9, 7],
       [3, 3, 8],
       [3, 0, 1],
       [0, 0, 6]])

In [103]:
print(random_array_6)

[[4 9 7]
 [3 3 8]
 [3 0 1]
 [0 0 6]]


In [104]:
np.unique(random_array_6)

array([0, 1, 3, 4, 6, 7, 8, 9])

In [121]:
a4 = np.random.randint(20, size=(3, 3, 4, 5))
a4

array([[[[13,  8, 14, 13,  9],
         [10,  0,  2, 16,  6],
         [18,  9,  9, 13, 11],
         [ 1, 14, 16, 16, 17]],

        [[14,  1, 19, 18,  0],
         [13, 10,  8,  1,  4],
         [12, 19, 10,  7, 17],
         [15,  0, 18,  7, 12]],

        [[16,  0, 12,  9, 14],
         [ 2, 16, 11,  5, 16],
         [ 9, 11, 10,  0,  8],
         [ 4,  5, 11, 17, 14]]],


       [[[10, 16,  7, 15, 18],
         [16, 14, 15, 13, 19],
         [ 9, 13,  3,  7, 17],
         [10,  0,  1, 11,  4]],

        [[ 6, 17, 14, 12, 11],
         [12, 16, 17,  0, 11],
         [ 1,  8,  1, 15,  2],
         [12,  4, 12, 11, 17]],

        [[18, 18, 18,  5,  7],
         [ 5,  5,  6, 16, 10],
         [14,  4, 14,  6, 13],
         [ 2, 12, 16, 14,  5]]],


       [[[ 8,  9, 12,  7, 14],
         [ 6,  2,  5, 17, 14],
         [ 9,  3, 15,  0,  3],
         [ 6,  0,  1,  2, 11]],

        [[15, 11,  4,  8, 13],
         [11,  7,  7, 19,  7],
         [13, 18,  3, 17,  1],
         [ 8, 15, 10,

In [122]:
a4[0]

array([[[13,  8, 14, 13,  9],
        [10,  0,  2, 16,  6],
        [18,  9,  9, 13, 11],
        [ 1, 14, 16, 16, 17]],

       [[14,  1, 19, 18,  0],
        [13, 10,  8,  1,  4],
        [12, 19, 10,  7, 17],
        [15,  0, 18,  7, 12]],

       [[16,  0, 12,  9, 14],
        [ 2, 16, 11,  5, 16],
        [ 9, 11, 10,  0,  8],
        [ 4,  5, 11, 17, 14]]])

In [125]:
a4[:2, :, :2, :2], a4.shape, a4.ndim

(array([[[[13,  8],
          [10,  0]],
 
         [[14,  1],
          [13, 10]],
 
         [[16,  0],
          [ 2, 16]]],
 
 
        [[[10, 16],
          [16, 14]],
 
         [[ 6, 17],
          [12, 16]],
 
         [[18, 18],
          [ 5,  5]]]]),
 (3, 3, 4, 5),
 4)

In [130]:
# the first four number in the inner most arrays
a4[:, :, :, 1:4]

array([[[[ 8, 14, 13],
         [ 0,  2, 16],
         [ 9,  9, 13],
         [14, 16, 16]],

        [[ 1, 19, 18],
         [10,  8,  1],
         [19, 10,  7],
         [ 0, 18,  7]],

        [[ 0, 12,  9],
         [16, 11,  5],
         [11, 10,  0],
         [ 5, 11, 17]]],


       [[[16,  7, 15],
         [14, 15, 13],
         [13,  3,  7],
         [ 0,  1, 11]],

        [[17, 14, 12],
         [16, 17,  0],
         [ 8,  1, 15],
         [ 4, 12, 11]],

        [[18, 18,  5],
         [ 5,  6, 16],
         [ 4, 14,  6],
         [12, 16, 14]]],


       [[[ 9, 12,  7],
         [ 2,  5, 17],
         [ 3, 15,  0],
         [ 0,  1,  2]],

        [[11,  4,  8],
         [ 7,  7, 19],
         [18,  3, 17],
         [15, 10, 18]],

        [[ 0,  8, 13],
         [ 2,  3,  0],
         [ 1,  5,  5],
         [19, 11, 18]]]])

## Manipulating and comparing arrays

### Arithmetic

In [134]:
a1 = np.array([1, 2, 3,])
a1

array([1, 2, 3])

In [135]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [136]:
a1 + ones

array([2., 3., 4.])

In [137]:
a1 - ones

array([0., 1., 2.])

In [138]:
a1 * ones

array([1., 2., 3.])

In [139]:
a1 / ones

array([1., 2., 3.])

In [140]:
a1 % ones

array([0., 0., 0.])

In [141]:
a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [142]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 11. , 18. ]])

In [147]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [149]:
a2 / a1

array([[1.  , 1.  , 1.1 ],
       [4.  , 2.75, 2.  ]])

In [151]:
# floor division removes the decimal (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [154]:
a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [155]:
a1

array([1, 2, 3])

In [162]:
a2 ** a1

array([[  1.   ,   4.   ,  35.937],
       [  4.   ,  30.25 , 216.   ]])

In [165]:
a1

array([1, 2, 3])

In [163]:
a1 / 2

array([0.5, 1. , 1.5])

In [164]:
a1 % 2

array([1, 0, 1])

In [166]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [167]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])