In [2]:
import numpy as np

## Data types and attributes

In [3]:
# Numpy's main datatype is ndarray

In [4]:
a1 = np.array([1, 2, 3, 4, 5])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5.5, 6.0]])

In [7]:
type(a2)

numpy.ndarray

In [9]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [ 7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [10]:
type(a3)

numpy.ndarray

In [11]:
a1 # array, vector, 1 dimension, shape 1,5

array([1, 2, 3, 4, 5])

In [14]:
a2 # array, maxtrix, 2 dimension or more, shape 2, 3
# automatically convert all the data to float, ndarray only can be of one type

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [15]:
a3 # array, matrix, 3 dimension, shape, 2,3,3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
np.shape(a1)

(5,)

In [20]:
np.shape(a2)

(2, 3)

In [21]:
np.shape(a3)

(2, 3, 3)

In [22]:
# print dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [24]:
a1.size, a2.size, a3.size

(5, 6, 18)

In [25]:
a1, a2, a3

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3.3],
        [4. , 5.5, 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [26]:
# no matter what type or shape the array is, the type allways is ndarray, is an universal data type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# create a dataframe from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.5  6.0

In [ ]:
s